palette:
  - [255, 230, 180, 255]  # Pastel yellow
  - [180, 230, 180, 255]  # Pastel green
  - [180, 210, 255, 255]  # Pastel blue
  - [255, 200, 180, 255]  # Pastel peach
  - [220, 190, 255, 255]  # Pastel purple
  - [255, 200, 220, 255]  # Pastel pink

text_color: [40, 40, 40, 255]  # Dark gray text
# canvas_background: [140, 140, 140, 255]  # Darker gray
canvas_background: [40, 40, 40, 255]  # Darker gray

font_family: Roboto
font_size: 16

default_width: 240
default_height: 160
padding: 20
